# Project information
site_name: 'Hello World'
site_description: 'Software Development and Tech Blog'
site_author: 'John McCracken'
site_url: 'https://blog.john-mccracken.com/'

# Repository
# repo_name: 'squidfunk/mkdocs-material2'
# repo_url: 'ccfcf'

# Copyright
copyright: 'Copyright &copy; 2018 John McCracken'

# Configuration
theme:
  name: 'material'
  logo:
    icon: 'language'
  palette:
    primary: 'red'
    accent: 'red'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/johnmccuk'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/john-mccracken-025846a5/'
    - type: 'twitter'
      link: 'https://twitter.com/johnmccuk'

# Google Analytics
google_analytics:
  - 'UA-87654290-1'
  - 'auto'

# Pages
pages:
    - Home: index.md
    - Posts:
      - "Isolating PHP with Docker Containers": IsolatingPHPwithDockerContainers.md
      - "Test Driven Development Mentality": TestDrivenDevelopmentMentality.md
      - "AWS Certification Ponderings": AWSCertificationPonderings.md
      - "Automate AWS security group with CloudFlare IPs": AutomateAwsSecurityGroupsCloudFlareIPs.md
      - "VIM Skills": VimSkills.md
      - "Setting up Webpack": SettingUpWebpack.md
      - "Swift in 5 minutes": SwiftInFiveMinutes.md
      - "Apple Watch Series 2 first impressions": AppleWatchImpressions.md
      - "Learning Angular2 Part 2: Basic Demo": LearningAngular2Part2BasicDemo.md
      - "Learning Angular2 Part 1: Setup": LearningAngular2Part1Setup.md
      - "My Development Setup": MyDevelopmentSetup.md